version: "3.9"

networks:
  mynet:
    name: mynet
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  state_checker_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: state_checker_api
    volumes:
      - .:/code  # <--  THIS line enables hot code reloading! and writes logs back to source Dir.
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - mynet
    ports:
      - "${REST_API_PORT}:${REST_API_PORT}"
    command: ["uvicorn", "main_api_startpoint:app", "--host", "0.0.0.0", "--port", "${REST_API_PORT}"]

  state_checker_check:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: state_checker_check
    volumes:
      - .:/code  # <--  THIS line enables hot code reloading! and writes logs back to source Dir.
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - mynet
    command: ["python", "src/check_tools.py"]
